# Generated by Django 2.2.6 on 2021-11-14 20:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradesbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='unique_code',
            field=models.CharField(help_text='Формат: назва класу + рік навчання, наприклад: 1b2019', max_length=7, unique=True, validators=[django.core.validators.RegexValidator('^[1-12]{1}[а-г]{1}[0-9]{4}$')]),
        ),
    ]
