# Generated by Django 2.2.6 on 2021-11-14 21:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradesbook', '0009_auto_20211114_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='unique_code',
            field=models.CharField(help_text='Формат: назва класу + рік навчання, наприклад: 1b2019', max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[1-9]{1}[a-z]{1}[0-9]{4}$')]),
        ),
    ]
