# Generated by Django 2.2.6 on 2020-07-09 17:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RightsSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('manager', 'Global manager rights'), ('teacher', 'Global teacher rights'), ('student', 'Global student rights'), ('parent', 'Global parent rights')),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1024)),
                ('subject', models.CharField(max_length=128)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(help_text='Format: nazwa klasy(cyfra zmałą literą) łącznie z rokiem zakończenia nauki - np: 1b2019', max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^[1-8]{1}[a-z]{1}[0-9]{4}$')])),
                ('name', models.CharField(help_text='Cyfra i mała litera bez spacji.', max_length=2)),
                ('year', models.IntegerField(help_text='Rok zakończenia nauki w formacie czterocyfrowym', validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(9999)])),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('unique_code', models.CharField(help_text='Format: dwuliterowy skrót nazwy przedmiotu z dodanymunikalnym kodem klasy np: Hi2c2019 (Historia w klasie 2cw roku szkolnym 2019)', max_length=8, unique=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yourgrades.SchoolClass')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('first_login', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=254)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubjectTeachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yourgrades.Subject')),
                ('teacher', models.ManyToManyField(to='yourgrades.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Mo', 'Poniedizałek'), ('Tu', 'Wtorek'), ('We', 'Środa'), ('Th', 'Czwartek'), ('Fr', 'Piątek'), ('St', 'Sobota')], max_length=2)),
                ('lesson_number', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11')], validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)])),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yourgrades.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('first_login', models.BooleanField(default=True)),
                ('birthday', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yourgrades.SchoolClass')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='yourgrades.Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yourgrades.Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('first_login', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yourgrades.Student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MailboxSent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recipient', models.CharField(max_length=64)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yourgrades.Message')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yourgrades.Sender')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MailboxReceived',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('read', models.BooleanField(default=False)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yourgrades.Message')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yourgrades.Recipient')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yourgrades.Sender')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('grade', models.IntegerField(validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(1)])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('manager_mode', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yourgrades.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yourgrades.Subject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CanceledGrades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('grade', models.IntegerField(validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(1)])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yourgrades.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yourgrades.Subject')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
