# Generated by Django 2.2.6 on 2021-11-13 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourgrades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='name',
            field=models.CharField(help_text='Digit + lowercase letter e.g.: 1a', max_length=2),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='unique_code',
            field=models.CharField(help_text='Format: class name + year e.g.: 1b2019', max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^[1-8]{1}[a-z]{1}[0-9]{4}$')]),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='year',
            field=models.IntegerField(help_text='Four-digit graduation year', validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='unique_code',
            field=models.CharField(help_text='Format: subject shortcut + class shortcut e.g.: Hi2c2019', max_length=8, unique=True),
        ),
    ]
