# Generated by Django 2.2.6 on 2021-11-14 11:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourgrades', '0002_auto_20211113_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canceledgrades',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='grades',
            name='weight',
        ),
        migrations.AlterField(
            model_name='canceledgrades',
            name='grade',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='grades',
            name='grade',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='name',
            field=models.CharField(help_text='Число + буква нижнього реєстру, напр.: 1a', max_length=2),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='unique_code',
            field=models.CharField(help_text='Формат: назва класу + рік навчання, наприклад: 1b2019', max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^[1-8]{1}[a-z]{1}[0-9]{4}$')]),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='year',
            field=models.IntegerField(help_text='Чотирьох-значний рік навчання', validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='unique_code',
            field=models.CharField(help_text='Формат: скорочена назва предмему + назва класу і їхній рік, наприклад : Hi2c2019', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='subjectdate',
            name='day',
            field=models.CharField(choices=[('Mo', 'Понеділок'), ('Tu', 'Вівторок'), ('We', 'Середа'), ('Th', 'Четвер'), ('Fr', "П'ятниця"), ('St', 'Субота')], max_length=2),
        ),
    ]
